# Generated by Django 3.1.1 on 2020-11-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='has_animation',
            field=models.BooleanField(default=False),
        ),
    ]
