# Generated by Django 3.1.1 on 2020-11-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0002_algorithm_has_animation'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='slug',
            field=models.SlugField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
